### ISSUE TITLE
implement logic on problem display screen

### ISSUE THREAD

**Issue by SabeetHossain** [Codepath-Android-2022-Group-1/Android4SymbolMath#19]
-quit button returns to home and resets all values related to the problem, sign, and user inputted smallest/largest number
-implement timer
-displays the problem correctly based on the generated problem
-after pressing submit checks if right
-if wrong attempt again
-question number(number next to the quit button) changes based on which question you are on
-favorite button, adds the problem to favorites

**Comment by OverBrewedLeaf** [comment]
Finished logic and display
